# Generated by Django 2.2.24 on 2021-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='parser',
        ),
    ]
